imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true
        #lifetime:      3600

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'MopaBootstrapBundle:Form:fields.html.twig'
    
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    java: /usr/bin/java
    filters:
        less:
            node: /usr/bin/node
            node_paths: [/usr/lib/node_modules]
            apply_to: "\.less$"
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    #spool:
    #    type: file
    #    path: %kernel.root_dir%/mailspool
    #antiflood:
    #    threshold:            99
    #    sleep:                0

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            tree: false
            timestampable: true

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Acme\UserBundle\Entity\User
    from_email:
        address:        %sender_address%
        sender_name:    %sender_name%
    registration:
        confirmation:
            enabled:    true # change to true for required email confirmation

mopa_bootstrap:
    form:
        show_legend: false # default is true
        show_child_legend: false # default is true
        error_type: inline # block or inline which is default

    # navbar:
    #         service:    my.navbar
            

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
            
    # my.navbar:
    #         class: '%mopa_bootstrap.navbar.generic%'
    #         scope: request
    #         arguments:
    #             - { leftmenu: @my.navbar.main_menu=, rightmenu: @my.navbar.right_menu= }
    #             - {}
    #             - { title: "Menu", titleRoute: "homepage", fixedTop: true, isFluid: false } #, template: AcmeBundle::sidebar.html.twig }
    #         tags:
    #             - { name: mopa_bootstrap.navbar, alias: frontendNavbar }
    # 
    #     my.navbar.menu_builder:
    #         class: Acme\Bundle\Menu\MenuBuilder
    #         scope: request
    #         arguments: [ '@knp_menu.factory', '@security.context' ]
    # 
    #     my.navbar.main_menu:
    #         class: Knp\Menu\MenuItem
    #         factory_service: my.navbar.menu_builder
    #         factory_method: createMainMenu
    #         arguments: [ '@request' ]
    #         scope: request
    #         tags:
    #             - { name: knp_menu.menu, alias: main }
    #     
    #     my.navbar.right_menu:
    #         class: Knp\Menu\MenuItem
    #         factory_service: my.navbar.menu_builder
    #         factory_method: createRightMenu
    #         arguments: [ '@request' ]
    #         scope: request
    #         tags:
    #             - { name: knp_menu.menu, alias: right }
    
    